Repository salesforce/policy_sentry, pull requests merged in 2019-11, with the labels that each got.

#37 Fixes #35
  policy_sentry/shared/data/access-level-overrides.yml
Labels: access-level-override

#38 Fix #31 - move documentation to ReadTheDocs
  .readthedocs.yml
  Pipfile
  Pipfile.lock
  docs/Makefile
  docs/appendix/implementation-strategy.rst
  docs/appendix/policy_sentry-as-a-python-package.rst
  docs/conf.py
  docs/contributing/contributing.rst
  docs/contributing/internals.rst
  docs/contributing/roadmap.rst
  docs/iam-knowledge/iam-policies.rst
  docs/iam-knowledge/minimization.rst
  docs/images/1-kms-create-grant-example.png
  docs/images/2-kms-key-arn-example.png
  docs/images/3-SSM-visual-editor.png
  docs/index.rst
  docs/introduction/comparison-to-similar-tools.rst
  docs/introduction/home.rst
  docs/make.bat
  docs/requirements.txt
  docs/terraform/terraform-demo.rst
  docs/terraform/terraform-modules.rst
  docs/user-guide/analyze-policy.rst
  docs/user-guide/command-cheat-sheet.rst
  docs/user-guide/downloading-policies.rst
  docs/user-guide/initialize.rst
  docs/user-guide/installation.rst
  docs/user-guide/querying-the-database.rst
  docs/user-guide/write-policy.rst
Labels: documentation

#36 Database Query from CLI capability
  CHANGELOG.md
  policy_sentry/bin/policy_sentry
  policy_sentry/command/__init__.py
  policy_sentry/command/query.py
  policy_sentry/shared/actions.py
  policy_sentry/shared/conditions.py
  policy_sentry/shared/database.py
  policy_sentry/shared/policy.py
  policy_sentry/shared/query.py
  test/test_access_level_overrides.py
  test/test_query.py
Labels: enhancement

#27 Proper dev environment
  Pipfile
  policy_sentry/command/analyze_iam_policy.py
  policy_sentry/command/initialize.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/shared/actions.py
  policy_sentry/shared/analyze.py
  policy_sentry/shared/arns.py
  policy_sentry/shared/conditions.py
  policy_sentry/shared/config.py
  policy_sentry/shared/database.py
  policy_sentry/shared/download.py
  policy_sentry/shared/file.py
  policy_sentry/shared/login.py
  policy_sentry/shared/minimize.py
  policy_sentry/shared/policy.py
  policy_sentry/shared/roles.py
  policy_sentry/shared/scrape.py
  tasks.py
Labels: enhancement

#41 Write-policy CRUD mode now allows users to request IAM actions that cannot be restricted to ARNs
  .gitignore
  CHANGELOG.md
  docs/user-guide/write-policy.rst
  examples/yml/crud-with-wildcard.yml
  policy_sentry/shared/policy.py
  policy_sentry/shared/query.py
  policy_sentry/shared/template.py
  setup.py
  test/test_query.py
  test/test_template.py
  test/test_write_policy.py
  test/test_yaml_validation.py
Labels: enhancement, high-priority

#44 Feat/analyze policies with attributes file
  .gitignore
  CHANGELOG.md
  Pipfile
  README.md
  docs/user-guide/analyze-policy.rst
  docs/user-guide/command-cheat-sheet.rst
  docs/user-guide/downloading-policies.rst
  examples/output-dir/policy-puma.json
  examples/output-dir/policy-zebu.json
  policy_sentry/bin/policy_sentry
  policy_sentry/command/__init__.py
  policy_sentry/command/analyze.py
  policy_sentry/command/analyze_iam_policy.py
  policy_sentry/command/download_policies.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/shared/actions.py
  policy_sentry/shared/analyze.py
  policy_sentry/shared/config.py
  policy_sentry/shared/constants.py
  policy_sentry/shared/data/audit/data-access-arn-list.txt
  policy_sentry/shared/data/audit/network-exposure.txt
  policy_sentry/shared/data/audit/privilege-escalation.txt
  policy_sentry/shared/data/audit/report-config.yml
  policy_sentry/shared/data/audit/resource-exposure.txt
  policy_sentry/shared/database.py
  policy_sentry/shared/download.py
  policy_sentry/shared/finding.py
  policy_sentry/shared/login.py
  policy_sentry/shared/policy.py
  policy_sentry/shared/query.py
  policy_sentry/shared/report.py
  policy_sentry/shared/roles.py
  setup.py
  tasks.py
  test/test_actions.py
  test/test_analyze.py
  test/test_arn_action_group.py
  test/test_arns.py
  test/test_expand_wildcard_actions.py
  test/test_minimize_wildcard_actions.py
  test/test_query.py
  test/test_write_policy.py
  test/test_yaml_validation.py
Labels: enhancement

#45 Fix/pep8 issues
  .pylintrc
  CHANGELOG.md
  policy_sentry/__init__.py
  policy_sentry/command/__init__.py
  policy_sentry/command/analyze.py
  policy_sentry/command/create_template.py
  policy_sentry/command/download_policies.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/shared/actions.py
  policy_sentry/shared/analyze.py
  policy_sentry/shared/arns.py
  policy_sentry/shared/conditions.py
  policy_sentry/shared/config.py
  policy_sentry/shared/constants.py
  policy_sentry/shared/database.py
  policy_sentry/shared/download.py
  policy_sentry/shared/file.py
  policy_sentry/shared/finding.py
  policy_sentry/shared/login.py
  policy_sentry/shared/minimize.py
  policy_sentry/shared/policy.py
  policy_sentry/shared/query.py
  policy_sentry/shared/report.py
  policy_sentry/shared/roles.py
  policy_sentry/shared/scrape.py
  policy_sentry/shared/template.py
  test/test_access_level_overrides.py
  test/test_analyze.py
  test/test_minimize_wildcard_actions.py
  test/test_yaml_validation.py
Labels: quick-fix
