Repository salesforce/policy_sentry, pull requests merged in 2020-05, with the labels that each got.

#179 Fixes overly verbose logging issue for one of the query functions.
  CHANGELOG.md
  policy_sentry/bin/cli.py
  policy_sentry/querying/actions.py
Labels: bug

#180 allow initialize to be used as a library function
  policy_sentry/bin/cli.py
  policy_sentry/command/initialize.py
Labels: cla:signed

#184 Fixes #182 - adds the ability to exclude some actions from the resulting policy
  CHANGELOG.md
  README.md
  docs/writing-policies/excluding-actions.md
  docs/writing-policies/skipping-resource-constraints.md
  examples/yml/crud-with-exclude-actions.yml
  mkdocs.yml
  policy_sentry/bin/cli.py
  policy_sentry/writing/sid_group.py
  policy_sentry/writing/template.py
  policy_sentry/writing/validate.py
  tasks.py
  test/writing/test_sid_group_crud.py
  test/writing/test_template.py
Labels: enhancement

#187 Point to a stable link to the aws_config hacking script
  README.md
Labels: cla:signed
