Repository salesforce/policy_sentry, pull requests merged in 2020-06, with the labels that each got.

#190 Auto update
  .editorconfig
  .github/scripts/update_data.py
  .github/workflows/update.yml
Labels: cla:signed

#192 Move from Pipenv to venv
  .editorconfig
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .pyup.yml
  .readthedocs.yml
  CHANGELOG.md
  Dockerfile
  Pipfile
  docs/contributing/documentation.md
  docs/contributing/iam-database.md
  docs/contributing/testing.md
  requirements-dev.txt
  requirements.txt
  setup.py
  tasks.py
  utils/run_tests.sh
  utils/update-brew.sh
Labels: delivery-related

#193 Pyup initial update
  .pylintrc
  docs/requirements.txt
  requirements-dev.txt
  requirements.txt
Labels: cla:missing

#194 Fixing documentation according to agreed format
  mkdocs.yml
Labels: cla:signed

#197 Fix GitHub publish action
  .github/workflows/publish.yml
Labels: delivery-related
