Repository salesforce/policy_sentry, pull requests merged in 2020-12, with the labels that each got.

#294 updating testing document with test strategy
  docs/contributing/testing.md
Labels: documentation

#304 Add GitHub workflow to combine Dependabot PRs into a single one
  .github/workflows/combine-prs.yml
  requirements-dev.txt
Labels: automation

#306 Fix automatic IAM definition update action
  .github/workflows/update.yml
Labels: cla:signed

#315 Fixes #296 - query all services for wildcard-only actions
  policy_sentry/bin/cli.py
  policy_sentry/command/query.py
  policy_sentry/querying/actions.py
  tasks.py
  test/command/__init__.py
  test/command/test_query_actions_click.py
  test/querying/test_all.py
Labels: bug

#316 Use version.py to control versions
  docs/contributing/versioning.md
  docs/requirements.txt
  policy_sentry/bin/cli.py
  policy_sentry/bin/version.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: cleanup

#317 Add method to get links to all AWS Actions
  policy_sentry/querying/actions.py
  test/querying/test_query_actions.py
Labels: enhancement
