Repository salesforce/policy_sentry, pull requests merged in 2020-01, with the labels that each got.

#80 Docker support; fixes issue with pre-bundled DB path
  .dockerignore
  CHANGELOG.md
  Dockerfile
  MANIFEST.in
  Pipfile
  README.md
  docs/contributing/contributing.rst
  docs/index.rst
  docs/user-guide/docker.rst
  docs/user-guide/initialize.rst
  docs/user-guide/usage-as-a-python-package.rst
  examples/third-party-package/example.py
  policy_sentry/analysis/analyze.py
  policy_sentry/bin/policy_sentry
  policy_sentry/command/write_policy.py
  policy_sentry/shared/constants.py
  policy_sentry/shared/data/aws.sqlite3
  policy_sentry/shared/database.py
  policy_sentry/util/file.py
  policy_sentry/writing/validate.py
  setup.py
  test/test_query.py
  test/test_template_validation.py
  test/test_write_policy.py
  test/test_yaml.py
  utils/download_docs.py
  utils/entrypoint.sh
Labels: enhancement

#81 Fixed an issue where keys in the condition keys table were being stored with extra spaces
  CHANGELOG.md
  policy_sentry/shared/database.py
Labels: quick-fix

#82 Auto generate readthedocs module docs from docstrings; code examples for usage as a library
  CHANGELOG.md
  Pipfile
  docs/conf.py
  docs/contributing/disclaimer.rst
  docs/contributing/documentation.rst
  docs/contributing/iam-database.rst
  docs/contributing/index.rst
  docs/contributing/internals.rst
  docs/contributing/project-structure.rst
  docs/contributing/roadmap.rst
  docs/contributing/testing.rst
  docs/contributing/versioning.rst
  docs/index.rst
  docs/introduction/home.rst
  docs/library-usage/examples/index.rst
  docs/library-usage/examples/querying.rst
  docs/library-usage/getting-started-with-the-library.rst
  docs/library-usage/index.rst
  docs/library-usage/reference/analyzing.rst
  docs/library-usage/reference/index.rst
  docs/library-usage/reference/querying.rst
  docs/library-usage/reference/utilities.rst
  docs/library-usage/reference/writing.rst
  docs/requirements.txt
  examples/library-usage/example.py
  examples/library-usage/querying/actions/get_actions_for_service.py
  examples/library-usage/querying/actions/get_actions_with_access_levels.py
  policy_sentry/analysis/analyze.py
  policy_sentry/analysis/finding.py
  policy_sentry/querying/actions.py
  policy_sentry/querying/all.py
  policy_sentry/querying/arns.py
  policy_sentry/querying/conditions.py
  policy_sentry/shared/database.py
  policy_sentry/writing/minimize.py
  policy_sentry/writing/policy.py
  tasks.py
Labels: documentation

#85 Tweak some functions to allow for direct method calls
  CHANGELOG.md
  README.md
  docs/index.rst
  docs/introduction/home.rst
  docs/library-usage/examples/analysis.rst
  docs/library-usage/examples/index.rst
  docs/library-usage/examples/querying.rst
  docs/library-usage/examples/writing.rst
  docs/library-usage/index.rst
  docs/user-guide/analyze-policy.rst
  docs/user-guide/write-policy.rst
  examples/input-dir/policy-puma.yml
  examples/input-dir/policy-zebu.yml
  examples/library-usage/writing/write_policy_with_access_levels.py
  examples/library-usage/writing/write_policy_with_actions.py
  examples/terraform/environments/iam-resources/files/example-role-jpwdp.yml.example
  examples/terraform/modules/generate-policy_sentry-yml/templates/vibranium-template.yml
  examples/yml/actions.yml
  examples/yml/crud-with-wildcard.yml
  examples/yml/crud.yml
  policy_sentry/bin/policy_sentry
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/shared/data/links.yml
  policy_sentry/writing/roles.py
  policy_sentry/writing/template.py
  policy_sentry/writing/validate.py
  test/test_template.py
  test/test_template_validation.py
  test/test_write_policy.py
  test/test_write_policy_library_usage.py
  test/test_yaml.py
  utils/run_tests.sh
Labels: enhancement

#87 Fix string literal comparison error with python 3.8
  policy_sentry/util/policy_files.py
  policy_sentry/writing/minimize.py
Labels: quick-fix

#86 Add Python 3.8 to Travis
  .travis.yml
Labels: cla:signed

#88 Add shell completion instructions and make some documentation tweaks
  README.md
  docs/introduction/home.rst
  docs/user-guide/installation.rst
Labels: documentation

#90 get_actions_with_access_level now supports 'all' so you can query literally all IAM actions that have Permissions management or other access levels
  CHANGELOG.md
  examples/library-usage/querying/actions/get_all_actions_with_access_level.py
  policy_sentry/bin/policy_sentry
  policy_sentry/querying/actions.py
  test/test_query.py
Labels: enhancement

#91 Provide Query function to get actions matching a condition, crud level, and raw ARN
  CHANGELOG.md
  examples/library-usage/querying/actions/get_actions_matching_condition_crud_and_arn.py
  policy_sentry/querying/actions.py
  policy_sentry/querying/conditions.py
  test/test_query.py
Labels: enhancement

#92 Refactor tests to use pytest
  .travis.yml
  Pipfile
  setup.py
  tasks.py
  test/test_query.py
  test/test_template.py
  utils/run_tests.sh
Labels: delivery-related

#93 Add GIF to the Readme
  README.md
  examples/asciinema/policy_sentry.cast
  examples/asciinema/policy_sentry_s3_v4.gif
Labels: documentation

#96 Update python example. Add Library usage to readme. Fix typo in readthedocs
  README.md
  docs/user-guide/write-policy.rst
  examples/library-usage/writing/write_policy_with_access_levels.py
Labels: documentation

#97 Query command improvements - yaml support, and wildcard actions at access levels
  .pylintrc
  CHANGELOG.md
  README.md
  docs/user-guide/command-cheat-sheet.rst
  docs/user-guide/querying-the-database.rst
  policy_sentry/command/query.py
  policy_sentry/querying/actions.py
  policy_sentry/querying/conditions.py
  tasks.py
  test/test_query.py
  utils/run_tests.sh
Labels: enhancement

#100 Quick fix: issue where Tagging was not being recognized in the write-policy YML templates
  .gitignore
  policy_sentry/bin/policy_sentry
  policy_sentry/writing/policy.py
  test/test_query.py
  test/test_write_policy_library_usage.py
Labels: bug, quick-fix

#103 Initialize command finishes instantly
  CHANGELOG.md
  README.md
  docs/introduction/home.rst
  docs/user-guide/initialize.rst
  policy_sentry/bin/policy_sentry
  policy_sentry/command/initialize.py
  policy_sentry/shared/constants.py
  policy_sentry/writing/template.py
  test/test_template.py
Labels: documentation, enhancement

#105 Add sqlite3 diff csv script
  .gitignore
  policy_sentry/shared/data/action_table.csv
  policy_sentry/shared/data/arn_table.csv
  policy_sentry/shared/data/aws.sqlite3
  policy_sentry/shared/data/condition_table.csv
  policy_sentry/shared/data/docs/list_alexaforbusiness.partial.html
  policy_sentry/shared/data/docs/list_amazonathena.partial.html
  policy_sentry/shared/data/docs/list_amazoncognitoidentity.partial.html
  policy_sentry/shared/data/docs/list_amazonec2instanceconnect.partial.html
  policy_sentry/shared/data/docs/list_amazonelasticcontainerregistry.partial.html
  policy_sentry/shared/data/docs/list_amazonelasticsearchservice.partial.html
  policy_sentry/shared/data/docs/list_amazonforecast.partial.html
  policy_sentry/shared/data/docs/list_amazonglacier.partial.html
  policy_sentry/shared/data/docs/list_amazoninspector.partial.html
  policy_sentry/shared/data/docs/list_amazonkinesisanalytics.partial.html
  policy_sentry/shared/data/docs/list_amazonmachinelearning.partial.html
  policy_sentry/shared/data/docs/list_amazonmanagedblockchain.partial.html
  policy_sentry/shared/data/docs/list_amazonmechanicalturk.partial.html
  policy_sentry/shared/data/docs/list_amazonpinpointemailservice.partial.html
  policy_sentry/shared/data/docs/list_amazonqldb.partial.html
  policy_sentry/shared/data/docs/list_amazonrds.partial.html
  policy_sentry/shared/data/docs/list_amazonrdsiamauthentication.partial.html
  policy_sentry/shared/data/docs/list_amazonresourcegrouptaggingapi.partial.html
  policy_sentry/shared/data/docs/list_amazonroute53domains.partial.html
  policy_sentry/shared/data/docs/list_amazontranscribe.partial.html
  policy_sentry/shared/data/docs/list_amazonworkspaces.partial.html
  policy_sentry/shared/data/docs/list_awsbackup.partial.html
  policy_sentry/shared/data/docs/list_awsbilling.partial.html
  policy_sentry/shared/data/docs/list_awscertificatemanagerprivatecertificateauthority.partial.html
  policy_sentry/shared/data/docs/list_awsconfig.partial.html
  policy_sentry/shared/data/docs/list_awscostandusagereport.partial.html
  policy_sentry/shared/data/docs/list_awselasticbeanstalk.partial.html
  policy_sentry/shared/data/docs/list_awselementalmediapackagevod.partial.html
  policy_sentry/shared/data/docs/list_awslambda.partial.html
  policy_sentry/shared/data/docs/list_awsmobilehub.partial.html
  policy_sentry/shared/data/docs/list_awsorganizations.partial.html
  policy_sentry/shared/data/docs/list_awspricelist.partial.html
  policy_sentry/shared/data/docs/list_awsprivatemarketplace.partial.html
  policy_sentry/shared/data/docs/list_awssavingsplans.partial.html
  policy_sentry/shared/data/docs/list_awssecuritytokenservice.partial.html
  policy_sentry/shared/data/docs/list_awsservicecatalog.partial.html
  policy_sentry/shared/data/docs/list_awsshield.partial.html
  policy_sentry/shared/data/docs/list_awssupport.partial.html
  policy_sentry/shared/data/docs/list_cloudwatchapplicationinsights.partial.html
  policy_sentry/shared/data/docs/list_datapipeline.partial.html
  policy_sentry/shared/data/docs/list_launchwizard.partial.html
  policy_sentry/shared/data/docs/list_networkmanager.partial.html
  utils/download_docs.py
Labels: aws-docs, cleanup

#107 Undefined name: output --> results
  examples/library-usage/querying/actions/get_actions_matching_condition_crud_and_arn.py
Labels: cla:signed

#109 Resolve bad url ref bracketing in README
  README.md
Labels: cla:signed

#106 Allow risky action analysis using list
  policy_sentry/analysis/analyze.py
  test/test_analyze.py
Labels: cla:signed
