Repository salesforce/policy_sentry, pull requests merged in 2020-11, with the labels that each got.

#270 Change minimize to a boolean flag with an option minimize-length argument
  policy_sentry/bin/cli.py
  policy_sentry/command/write_policy.py
Labels: cla:signed, minor

#273 docs formatting
  docs/other/initialize.md
  docs/other/terraform.md
Labels: cla:signed

#275 removing CHANGELOG.md file
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
Labels: cleanup

#277 Migrate terraform module
  .gitignore
  .pre-commit-config.yaml
  terraform_module/README.md
  terraform_module/demo/main.tf
  terraform_module/demo/terraform.tfvars
  terraform_module/demo/variables.tf
  terraform_module/iam-policies/README.md
  terraform_module/iam-policies/main.tf
  terraform_module/iam-policies/outputs.tf
  terraform_module/iam-policies/provider.tf
  terraform_module/iam-policies/variables.tf
  terraform_module/main.tf
  terraform_module/outputs.tf
  terraform_module/provider.tf
  terraform_module/ps-template/README.md
  terraform_module/ps-template/main.tf
  terraform_module/ps-template/outputs.tf
  terraform_module/ps-template/provider.tf
  terraform_module/ps-template/variables.tf
  terraform_module/variables.tf
Labels: terraform

#282 Adds support for Terraform 0.13
  README.md
  terraform_module/README.md
  terraform_module/demo/main.tf
  terraform_module/demo/terraform.tfvars
  terraform_module/iam-policies/README.md
  terraform_module/iam-policies/provider.tf
  terraform_module/outputs.tf
  terraform_module/provider.tf
  terraform_module/ps-template/README.md
  terraform_module/ps-template/main.tf
  terraform_module/ps-template/provider.tf
  terraform_module/variables.tf
Labels: terraform

#284 Unexpected output when working with ARNs that have a path in them
  policy_sentry/bin/cli.py
  policy_sentry/util/arns.py
  test/files/test_gh_204_multiple_resource_types_wildcards.json
  test/util/test_arns.py
  test/writing/test_write_policy_library_usage.py
Labels: cla:missing, enhancement, high-priority, minor
