Repository salesforce/policy_sentry, pull requests merged in 2020-10, with the labels that each got.

#247 renaming github action test.yml to ci.yml and name to continuous-integration
  .github/workflows/ci.yml
Labels: cla:signed

#246 fix None type scenario in get_actions_for_service
  policy_sentry/querying/actions.py
  test/querying/test_query_actions.py
Labels: cla:signed

#249 updating build badge to github actions CI badge in README.md
  README.md
Labels: cla:signed

#250 adding unit tests for util/conditions.py is_condition_key_match method
  test/util/test_conditions.py
Labels: cla:signed

#259 Ensured minimization won't break if resource path contains special characters and improve the unit tests for minimization
  policy_sentry/util/text.py
  policy_sentry/writing/sid_group.py
  test/util/test_arns.py
  test/writing/test_minimize.py
Labels: bug

#261 Add `--resource-type` flag to `policy_sentry query action-table` command
  CHANGELOG.md
  docs/querying/action-table.md
  policy_sentry/command/query.py
  policy_sentry/querying/actions.py
  tasks.py
  test/querying/test_query_actions.py
Labels: cla:signed, enhancement

#265 fix cheat sheet for resource type
  docs/cheat-sheet.md
Labels: cla:signed, documentation

#263 Updates to policy_sentry to more easily allow terraform to consume policies
  policy_sentry/command/write_policy.py
Labels: cla:signed

#267 Fix for #266 SID contains dash
  CHANGELOG.md
  policy_sentry/writing/sid_group.py
  test/writing/test_sid_group_actions.py
Labels: cla:signed

#269 fix logging bug
  CHANGELOG.md
  policy_sentry/__init__.py
  policy_sentry/command/create_template.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  requirements-dev.txt
  requirements.txt
Labels: bug, cla:signed

#260 adding release drafter github action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  docs/contributing/release-drafter.md
  mkdocs.yml
Labels: cla:signed, delivery-related
