Repository salesforce/policy_sentry, pull requests merged in 2020-02, with the labels that each got.

#110 Merge pull request #110 from kmcquade/fix/add-logging-again
  .pylintrc
  CHANGELOG.md
  docs/contributing/testing.rst
  docs/index.rst
  docs/user-guide/analyze-policy.rst
  docs/user-guide/downloading-policies.rst
  docs/user-guide/querying-the-database.rst
  docs/user-guide/write-policy.rst
  policy_sentry/__init__.py
  policy_sentry/analysis/analyze.py
  policy_sentry/analysis/report.py
  policy_sentry/bin/policy_sentry
  policy_sentry/command/analyze.py
  policy_sentry/command/create_template.py
  policy_sentry/command/download_policies.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/configuration/access_level_overrides.py
  policy_sentry/configuration/analysis.py
  policy_sentry/configuration/config_directory.py
  policy_sentry/downloading/download.py
  policy_sentry/downloading/login.py
  policy_sentry/querying/actions.py
  policy_sentry/scraping/awsdocs.py
  policy_sentry/scraping/scrape.py
  policy_sentry/shared/constants.py
  policy_sentry/shared/database.py
  policy_sentry/util/access_levels.py
  policy_sentry/util/arns.py
  policy_sentry/util/file.py
  policy_sentry/util/policy_files.py
  policy_sentry/writing/minimize.py
  policy_sentry/writing/policy.py
  policy_sentry/writing/roles.py
  policy_sentry/writing/validate.py
  tasks.py
Labels: cleanup, enhancement

#111 Get access levels from statement
  policy_sentry/analysis/analyze.py
  policy_sentry/util/policy_files.py
  test/test_analyze.py
Labels: cla:signed

#116 Reformat with Python Black because it looks better than autopep8
  .pylintrc
  CHANGELOG.md
  Pipfile
  policy_sentry/__init__.py
  policy_sentry/analysis/analyze.py
  policy_sentry/command/create_template.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/configuration/access_level_overrides.py
  policy_sentry/configuration/config_directory.py
  policy_sentry/querying/actions.py
  policy_sentry/querying/all.py
  policy_sentry/querying/arns.py
  policy_sentry/querying/conditions.py
  policy_sentry/scraping/awsdocs.py
  policy_sentry/scraping/scrape.py
  policy_sentry/shared/constants.py
  policy_sentry/shared/database.py
  policy_sentry/util/access_levels.py
  policy_sentry/util/actions.py
  policy_sentry/util/arns.py
  policy_sentry/util/conditions.py
  policy_sentry/util/file.py
  policy_sentry/util/policy_files.py
  policy_sentry/util/text.py
  policy_sentry/writing/minimize.py
  policy_sentry/writing/sid_group.py
  policy_sentry/writing/template.py
  policy_sentry/writing/validate.py
  tasks.py
  test/analysis/test_analyze.py
  test/command/test_write_policy.py
  test/querying/test_query_actions.py
  test/querying/test_query_arns.py
  test/querying/test_query_conditions.py
  test/util/test_access_levels.py
  test/util/test_arns.py
  test/util/test_policy_files.py
  test/writing/test_minimize.py
  test/writing/test_sid_group.py
  test/writing/test_validate.py
  test/writing/test_write_policy_library_usage.py
  test/writing/test_yaml.py
Labels: cleanup

#117 The initialize command is now completely optional
  CHANGELOG.md
  README.md
  docs/index.rst
  docs/introduction/home.rst
  docs/user-guide/command-cheat-sheet.rst
  docs/user-guide/initialize.rst
  docs/user-guide/write-policy.rst
  policy_sentry/configuration/config_directory.py
  policy_sentry/shared/constants.py
  policy_sentry/writing/sid_group.py
Labels: enhancement

#120 Fixes #118 and Fixes #119
  CHANGELOG.md
  examples/yml/tagging.yml
  policy_sentry/bin/policy_sentry
  policy_sentry/command/create_template.py
  policy_sentry/querying/arns.py
  policy_sentry/writing/sid_group.py
  test/command/test_write_policy.py
Labels: bug

#121 Improved logging
  docs/user-guide/querying-the-database.rst
  docs/user-guide/write-policy.rst
  policy_sentry/analysis/analyze.py
  policy_sentry/command/create_template.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/configuration/access_level_overrides.py
  policy_sentry/configuration/config_directory.py
  policy_sentry/scraping/scrape.py
  policy_sentry/shared/database.py
  policy_sentry/util/logging.py
  policy_sentry/writing/validate.py
Labels: cleanup

#123 Fix/ignore empty crud sections
  CHANGELOG.md
  examples/terraform/modules/generate-policy_sentry-yml/main.tf
  examples/terraform/modules/generate-policy_sentry-yml/templates/policy-sentry-template.yml
  policy_sentry/bin/policy_sentry
  policy_sentry/writing/sid_group.py
  test/command/test_write_policy.py
  test/writing/test_yaml.py
Labels: enhancement

#127 Fixes #126 - "if block checks for the same condition on both branches"
  CHANGELOG.md
  utils/download_docs.py
Labels: cleanup

#128 Updated Terraform module
  CHANGELOG.md
  README.md
  docs/contributing/iam-database.rst
  docs/index.rst
  docs/introduction/home.rst
  docs/terraform/terraform-demo.rst
  docs/terraform/terraform-modules.rst
  docs/user-guide/command-cheat-sheet.rst
  examples/terraform/README.md
  examples/terraform/environments/iam-resources/files/.gitkeep
  examples/terraform/environments/iam-resources/files/example-role-jpwdp.json.example
  examples/terraform/environments/iam-resources/files/example-role-jpwdp.yml.example
  examples/terraform/environments/iam-resources/main.tf
  examples/terraform/environments/iam-resources/outputs.tf
  examples/terraform/environments/iam-resources/provider.tf
  examples/terraform/environments/standard-resources/main.tf
  examples/terraform/environments/standard-resources/outputs.tf
  examples/terraform/environments/standard-resources/policy_sentry.tf
  examples/terraform/environments/standard-resources/provider.tf
  examples/terraform/modules/generate-iam-policies/README.md
  examples/terraform/modules/generate-iam-policies/main.tf
  examples/terraform/modules/generate-iam-policies/outputs.tf
  examples/terraform/modules/generate-iam-policies/variables.tf
  examples/terraform/modules/generate-policy_sentry-yml/README.md
  examples/terraform/modules/generate-policy_sentry-yml/main.tf
  examples/terraform/modules/generate-policy_sentry-yml/outputs.tf
  examples/terraform/modules/generate-policy_sentry-yml/provider.tf
  examples/terraform/modules/generate-policy_sentry-yml/templates/policy-sentry-template.yml
  examples/terraform/modules/generate-policy_sentry-yml/variables.tf
  examples/terraform/requirements.txt
  tasks.py
Labels: documentation, enhancement, terraform

#133 Change bs4 to beautifulsoup4 for dependency pinning
  Pipfile
  setup.py
Labels: cla:signed

#137 Fix logging with click_log
  CHANGELOG.md
  Pipfile
  docs/user-guide/querying/action-table.rst
  docs/user-guide/querying/arn-table.rst
  docs/user-guide/querying/condition-table.rst
  docs/user-guide/writing-policies/actions-mode.rst
  docs/user-guide/writing-policies/crud-mode.rst
  docs/user-guide/writing-policies/folder-mode.rst
  policy_sentry/command/create_template.py
  policy_sentry/command/initialize.py
  policy_sentry/command/query.py
  policy_sentry/command/write_policy.py
  policy_sentry/command/write_policy_dir.py
  policy_sentry/util/logging.py
  policy_sentry/writing/sid_group.py
  setup.py
Labels: bug
