Repository salesforce/policy_sentry, pull requests merged in 2021-04, with the labels that each got.

#349 FIxed terraform format
  terraform_module/README.md
Labels: cla:missing

#351 Fixed issue where readthedocs wasn't building due to an issue reading from writing.sid_group
  mkdocs.yml
Labels: documentation

#353 Fix Excluded Actions
  examples/yml/crud-with-exclude-actions-empty-sid.yml
  policy_sentry/writing/sid_group.py
  test/writing/test_sid_group_crud.py
Labels: cla:signed

#354 Fix readthedocs
  docs/writing-policies/actions-mode.md
  docs/writing-policies/crud-mode.md
Labels: cla:signed

#355 Fix PyUp with GitHub actions workaround
  .github/workflows/combine-prs.yml
  .github/workflows/python-dependency-updater.yml
Labels: dependencies

#357 Add version bump automation
  .github/workflows/bump-version.yml
  utils/bump-version.sh
Labels: automation

#358 Replace --wildcard-only with --resource-type "*" in README
  README.md
Labels: cla:missing

#360 Allow creating multiple policies in the same folder using the Terraform module
  terraform_module/ps-template/main.tf
Labels: cla:signed
